export const PLAN_FEATURES = {
  roots: {
    adSize: "small",
    adScope: "regional",
    discoveryPriority: "normal",
    discoveryFixed: false,
    newsArticles: 0,
    monthlyReport: false,
    simpleReport: false,
    businessHubAccess: false,
    realtimeDashboard: false,
    abTest: false,
    cheerNotificationLogo: false,
    snsShouting: 0,
    quarterlyMtg: false,
    monthlyMtg: false,
    pressRelease: false,
    roadmapAccess: false,
  },
  roots_plus: {
    adSize: "medium",
    adScope: "regional",
    discoveryPriority: "high",
    discoveryFixed: false,
    newsArticles: 1,
    monthlyReport: false,
    simpleReport: true,
    businessHubAccess: false,
    realtimeDashboard: false,
    abTest: false,
    cheerNotificationLogo: false,
    snsShouting: 0,
    quarterlyMtg: false,
    monthlyMtg: false,
    pressRelease: false,
    roadmapAccess: false,
  },
  signal: {
    adSize: "medium",
    adScope: "national",
    discoveryPriority: "normal",
    discoveryFixed: false,
    newsArticles: 1,
    monthlyReport: true,
    simpleReport: false,
    businessHubAccess: false,
    realtimeDashboard: false,
    abTest: false,
    cheerNotificationLogo: true,
    snsShouting: 1,
    quarterlyMtg: false,
    monthlyMtg: false,
    pressRelease: false,
    roadmapAccess: false,
  },
  presence: {
    adSize: "large",
    adScope: "national",
    discoveryPriority: "high",
    discoveryFixed: true,
    newsArticles: 2,
    monthlyReport: true,
    simpleReport: false,
    businessHubAccess: true,
    realtimeDashboard: false,
    abTest: true,
    cheerNotificationLogo: true,
    snsShouting: 3,
    quarterlyMtg: true,
    monthlyMtg: false,
    pressRelease: false,
    roadmapAccess: false,
  },
  legacy: {
    adSize: "hero",
    adScope: "national",
    discoveryPriority: "top",
    discoveryFixed: true,
    newsArticles: 4,
    monthlyReport: true,
    simpleReport: false,
    businessHubAccess: true,
    realtimeDashboard: true,
    abTest: true,
    cheerNotificationLogo: true,
    snsShouting: 999,
    quarterlyMtg: false,
    monthlyMtg: true,
    pressRelease: true,
    roadmapAccess: true,
  },
} as const;

export const NO_PLAN_FEATURES = {
  adSize: null,
  adScope: null,
  discoveryPriority: "normal",
  discoveryFixed: false,
  newsArticles: 0,
  monthlyReport: false,
  simpleReport: false,
  businessHubAccess: false,
  realtimeDashboard: false,
  abTest: false,
  cheerNotificationLogo: false,
  snsShouting: 0,
  quarterlyMtg: false,
  monthlyMtg: false,
  pressRelease: false,
  roadmapAccess: false,
} as const;

export function getPlanFeatures(plan: string | null) {
  if (!plan) return NO_PLAN_FEATURES;
  return PLAN_FEATURES[plan as keyof typeof PLAN_FEATURES] ?? NO_PLAN_FEATURES;
}

export const PLAN_PRIORITY: Record<string, number> = {
  legacy: 4,
  presence: 3,
  signal: 2,
  roots_plus: 1,
  roots: 0,
};
